spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: letshop

  mongodb:
    database: ${MONGODB_DATABASE}
    uri: ${MONGODB_URI}

  jwt:
    secret: ${SECRET}
    expiration: ${JWT_EXPIRATION}
  data:
    redis:
      host: localhost
      port: 6379

authentica:
  api-key: ${AUTHENTICA_API_KEY}


moyasar:
  base-url: https://api.moyasar.com/v1
  secret-key: ${MOYASAR_SECRET_KEY}
  publishable-key: ${MOYASAR_PUBLISHABLE_KEY}
  callback-url: https://example.com/payment/callback
logging:
  level:
    org.springframework.security: DEBUG