

spring:
  application:
    name: letshop
  mongodb:
    database: ${MONGODB_DATABASE:lets-shop}
    uri: ${MONGODB_URI:mongodb+srv://meer1khalifa_db_user:LlJomYQkiWQAncmI@billboard.ydhijvf.mongodb.net/?appName=billboard}
